project:
  type: website
  output-dir: docs

website:
  title: "Docker Tutorial"
  navbar:
    left:
      - text: Tutorial
        href: docker-setup-howto.qmd
      - text: Slides
        href: docker-setup-slides.qmd
